import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';

// Codex-supported hook events (as of v0.124.0-alpha.3, April 2026).
// PermissionRequest added on top of the original 5 Claude Code events.
const CODEX_SUPPORTED_EVENTS = new Set([
  'SessionStart', 'UserPromptSubmit',
  'PreToolUse', 'PostToolUse', 'PermissionRequest', 'Stop',
]);

// Capture the hooks-dir-relative .cjs path from a settings.json hook command.
// Must match BOTH the plain `node .claude/hooks/x.cjs` form AND the shipped
// runner form `bash -c 'h=.claude/hooks/haily-node.sh; s=.claude/hooks/x.cjs; …'`
// — the catalog uses the latter, so a `node …`-only pattern matched nothing.
const HOOK_CJS_RE = /\.claude\/hooks\/([^\s"';]+\.cjs)/;

export interface CodexHookEntry {
  event: string;
  command: { script: string; timeout_sec?: number };
  matcher?: string;
}

// Events where Codex accepts `additionalContext` (verified against
// developers.openai.com/codex/hooks, 6/2026). For every OTHER event Codex
// rejects the field, so the wrapper strips it. Field is NESTED at
// hookSpecificOutput.additionalContext — the prior top-level delete was a no-op.
const ADDITIONAL_CONTEXT_SUPPORTED_EVENTS = [
  'SessionStart', 'SubagentStart', 'PreToolUse', 'PostToolUse', 'UserPromptSubmit',
];

/**
 * Generate source of a Codex-compatibility wrapper for a single Claude Code hook script.
 *
 * What the wrapper translates:
 *   - Exit-code-2 block (Claude Code) → `{permissionDecision:"deny"}` JSON with exit 0 (Codex)
 *   - Strips `additionalContext` (nested + top-level) for events that don't accept it
 *   - Forwards stdin/stdout/stderr transparently for all other cases
 *
 * @param originalScriptPath - Absolute path to the hook .cjs being wrapped.
 * @param timeoutMs          - Spawn timeout baked into the wrapper; defaults to 30000ms
 *                             when the source hook entry declares no `timeout`.
 */
export function generateHookWrapper(originalScriptPath: string, timeoutMs = 30000): string {
  // JSON.stringify produces a safe string literal for embedding in generated source.
  const escaped = JSON.stringify(originalScriptPath);
  const supported = JSON.stringify(ADDITIONAL_CONTEXT_SUPPORTED_EVENTS);
  const timeout = Number.isFinite(timeoutMs) && timeoutMs > 0 ? Math.floor(timeoutMs) : 30000;
  return `'use strict';
// Codex-compatibility wrapper — auto-generated by HailyKit. Do not edit.
// Wraps: ${path.basename(originalScriptPath)}
const { spawnSync } = require('child_process');
const ADDITIONAL_CONTEXT_SUPPORTED = new Set(${supported});

const chunks = [];
process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin.on('data', c => chunks.push(c));
process.stdin.on('end', () => {
  const input = chunks.join('');
  // Detect the hook event so additionalContext is only stripped where Codex rejects it.
  let event = null;
  try { event = JSON.parse(input).hook_event_name || null; } catch {}

  const result = spawnSync(process.execPath, [${escaped}], {
    input,
    encoding: 'utf8',
    timeout: ${timeout},
    maxBuffer: 10 * 1024 * 1024,
  });

  // Claude Code signals block via exit-code 2 + JSON stdout {reason?}.
  // Codex expects exit 0 + JSON stdout {permissionDecision:"deny"}.
  if (result.status === 2) {
    let reason = '';
    try { reason = JSON.parse(result.stdout || '{}').reason || ''; } catch {}
    process.stdout.write(JSON.stringify({ permissionDecision: 'deny', reason }) + '\\n');
    process.exit(0);
  }

  if (result.status !== 0) {
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.status ?? 1);
  }

  if (result.stdout) {
    try {
      const out = JSON.parse(result.stdout);
      // Strip additionalContext only for events Codex doesn't accept it on.
      // Default-keep when the event is undetectable (matches latest-Codex behavior).
      if (event && !ADDITIONAL_CONTEXT_SUPPORTED.has(event)) {
        if (out.hookSpecificOutput) delete out.hookSpecificOutput.additionalContext;
        delete out.additionalContext;
      }
      process.stdout.write(JSON.stringify(out) + '\\n');
    } catch {
      // Non-JSON stdout: forward as-is
      process.stdout.write(result.stdout);
    }
  }
});
`;
}

/**
 * Return a content-addressed filename for a wrapper script.
 * Uses the first 8 hex chars of SHA-256 of the original path so two hooks
 * with the same basename in different directories never collide.
 *
 * @param originalPath - Absolute path to the original hook script.
 * @returns e.g. "compat-a1b2c3d4-my-hook.cjs"
 */
export function wrapperFilename(originalPath: string): string {
  const hash = crypto.createHash('sha256').update(originalPath).digest('hex').slice(0, 8);
  return `compat-${hash}-${path.basename(originalPath)}`;
}

/**
 * Write Codex-compatible wrapper scripts for every plain .cjs hook in destHooksDir.
 * Skips files that are already wrappers (compat-* prefix).
 *
 * @param destHooksDir   - Absolute path to the provider's hooks/ directory.
 * @param timeoutsByPath - Optional map of original-hook abs path → timeout (ms),
 *                         sourced from settings.json hook entries. Missing → 30000.
 * @returns Map of originalAbsPath → wrapperAbsPath.
 */
export function installHookWrappers(
  destHooksDir: string,
  timeoutsByPath?: Map<string, number>,
): Map<string, string> {
  const wrapperMap = new Map<string, string>();
  if (!fs.existsSync(destHooksDir)) return wrapperMap;

  for (const entry of fs.readdirSync(destHooksDir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith('.cjs')) continue;
    if (entry.name.startsWith('compat-')) continue; // never wrap a wrapper

    const originalPath = path.join(destHooksDir, entry.name);
    const wrapperName = wrapperFilename(originalPath);
    const wrapperPath = path.join(destHooksDir, wrapperName);

    const timeoutMs = timeoutsByPath?.get(originalPath) ?? 30000;
    fs.writeFileSync(wrapperPath, generateHookWrapper(originalPath, timeoutMs), 'utf8');
    wrapperMap.set(originalPath, wrapperPath);
  }
  return wrapperMap;
}

/**
 * Build the hooks.json array for Codex, translating settings.json hook config.
 * Only includes Codex-supported events; command paths are rewritten to the
 * corresponding wrapper script so protocol translation happens at runtime.
 *
 * @param allHooks    - settings.json `hooks` section (unknown shape at boundary).
 * @param destHooksDir - Absolute path to ~/.codex/hooks/.
 * @param wrapperMap  - originalPath → wrapperPath from installHookWrappers().
 */
export function buildCodexHooksJson(
  allHooks: unknown,
  destHooksDir: string,
  wrapperMap: Map<string, string>,
): CodexHookEntry[] {
  const entries: CodexHookEntry[] = [];
  if (typeof allHooks !== 'object' || allHooks === null) return entries;

  for (const [event, groups] of Object.entries(allHooks as Record<string, unknown>)) {
    if (!CODEX_SUPPORTED_EVENTS.has(event)) continue;

    for (const group of (Array.isArray(groups) ? groups : [])) {
      if (typeof group !== 'object' || group === null) continue;
      const g = group as Record<string, unknown>;
      const hookList = Array.isArray(g.hooks) ? g.hooks : [];

      for (const hook of hookList) {
        if (typeof hook !== 'object' || hook === null) continue;
        const h = hook as Record<string, unknown>;
        if (h.type !== 'command' || typeof h.command !== 'string') continue;

        const m = h.command.match(HOOK_CJS_RE);
        if (!m) continue;

        const origScript = path.join(destHooksDir, m[1]);
        // Prefer the wrapper; fall back to original if wrapper wasn't generated.
        const useScript = wrapperMap.get(origScript) ?? origScript;
        const absScript = useScript.replace(/\\/g, '/');

        const entry: CodexHookEntry = {
          event,
          command: { script: `node "${absScript}"` },
        };
        if (typeof g.matcher === 'string') entry.matcher = g.matcher;
        if (typeof h.timeout === 'number') entry.command.timeout_sec = h.timeout;

        entries.push(entry);
      }
    }
  }
  return entries;
}

/**
 * Build a map of original-hook abs path → declared timeout (ms) from settings hooks.
 * Used to bake the right spawn timeout into each generated wrapper. Hooks without a
 * `timeout` field are simply absent (the wrapper falls back to 30000ms).
 *
 * @param allHooks     - settings.json `hooks` section (unknown shape at boundary).
 * @param destHooksDir - Absolute path to ~/.codex/hooks/.
 */
export function buildTimeoutsByPath(allHooks: unknown, destHooksDir: string): Map<string, number> {
  const map = new Map<string, number>();
  if (typeof allHooks !== 'object' || allHooks === null) return map;

  for (const groups of Object.values(allHooks as Record<string, unknown>)) {
    for (const group of (Array.isArray(groups) ? groups : [])) {
      if (typeof group !== 'object' || group === null) continue;
      const hookList = Array.isArray((group as Record<string, unknown>).hooks)
        ? (group as Record<string, unknown>).hooks as unknown[] : [];
      for (const hook of hookList) {
        if (typeof hook !== 'object' || hook === null) continue;
        const h = hook as Record<string, unknown>;
        if (typeof h.command !== 'string' || typeof h.timeout !== 'number') continue;
        const m = h.command.match(HOOK_CJS_RE);
        if (!m) continue;
        map.set(path.join(destHooksDir, m[1]), h.timeout);
      }
    }
  }
  return map;
}

/**
 * Enable the hooks feature flag in ~/.codex/config.toml.
 * Required by Codex CLI before it processes hooks.json.
 *
 * Strategy (idempotent):
 *   1. If already managed (sentinel present) — no-op
 *   2. If [features] section exists — inject `hooks = true` after it
 *   3. Otherwise — append a HailyKit-managed block
 *
 * @param providerDir - Absolute path to ~/.codex/.
 */
export function writeCodexConfigToml(providerDir: string): void {
  const configPath = path.join(providerDir, 'config.toml');
  const SENTINEL = '# --- hailykit-hooks-start ---';
  const SENTINEL_END = '# --- hailykit-hooks-end ---';

  let content = '';
  if (fs.existsSync(configPath)) {
    content = fs.readFileSync(configPath, 'utf8');
    if (content.includes(SENTINEL)) return; // already present

    if (content.includes('[features]')) {
      // Inject into existing section — avoid duplicate key if hooks already there.
      if (!content.includes('hooks = true')) {
        content = content.replace(
          /\[features\]/,
          '[features]\nhooks = true  # added by hailykit',
        );
        fs.writeFileSync(configPath, content, 'utf8');
      }
      return;
    }
  }

  const block = `\n${SENTINEL}\n[features]\nhooks = true\n${SENTINEL_END}\n`;
  fs.mkdirSync(providerDir, { recursive: true });
  fs.writeFileSync(configPath, content + block, 'utf8');
}
